version: '3.8'
services:

    #PHP Service
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: task-management-app
        restart: unless-stopped
        tty: true
        depends_on:
            - mysql
        entrypoint: ./docker/entrypoint-app.sh
        volumes:
            - ./:/var/www
            - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
        networks:
            - task-management-network

    webserver:
        image: nginx:stable
        container_name: task-management-nginx
        restart: always
        links:
            - app
        tty: true
        ports:
            - "8090:80"
        volumes:
            - ./:/var/www
            - ./docker/nginx/conf.d/app.conf:/etc/nginx/conf.d/default.conf
        networks:
            - task-management-network
    mysql:
        image: mysql:8
        command: --default-authentication-plugin=mysql_native_password
        container_name: task-management.mysql
        restart: always
        volumes:
            - mysql8data:/var/lib/mysql
        environment:
            MYSQL_DATABASE: task-management
            MYSQL_PASSWORD: secret
            MYSQL_ROOT_PASSWORD: 123456
        networks:
            - task-management-network

#Docker Networks
networks:
    task-management-network:
        driver: bridge

#Volumes
volumes:
    mysql8data:
        driver: local
